"""Per-pool subclustering settings, taken verbatim from the original subcluster_*.py.

Each pool is a group of initial Leiden clusters that share a lineage. `filter_genes`
decides which cells may enter the pool (a cell needs a non-zero count for at least one
of them); `feature_genes` replaces the usual highly-variable selection, so the
subclustering splits on lineage biology rather than on the dominant axis of variance;
`programs` names each resulting subcluster after its highest-scoring signature.
"""

POOLS = {
    "tnk": {
        "label": "T/NK",
        "source": "subcluster_cl0_tcell_only.py",
        "clusters": ["0"],
        "resolution": 0.3,
        "n_pcs": 15,
        "filter_genes": ["CD3D", "CD3E", "CD3G", "TRAC"],
        "feature_genes": [
            "CD3D",
            "CD3E",
            "CD3G",
            "TRAC",
            "CD4",
            "CD8A",
            "CD8B",
            "CCR7",
            "SELL",
            "TCF7",
            "IL7R",
            "CD27",
            "CD28",
            "GZMA",
            "GZMK",
            "GNLY",
            "PRF1",
            "NKG7",
            "PDCD1",
            "LAG3",
            "HAVCR2",
            "TIGIT",
            "CTLA4",
            "TOX",
            "CD69",
            "FOXP3",
            "IL2RA",
            "TBX21",
            "GATA3",
            "RORC",
            "CXCR5",
            "CCR4",
            "KLRB1",
            "KLRD1",
            "KLRF1",
            "FCGR3A",
            "NCAM1",
            "KLRC1",
            "MKI67",
        ],
        "programs": {
            "naive_memory": ["CCR7", "SELL", "TCF7", "IL7R", "CD27", "CD28"],
            "cytotoxic_effector": ["GZMA", "GZMK", "PRF1", "GNLY", "NKG7"],
            "exhausted": ["PDCD1", "LAG3", "HAVCR2", "TIGIT", "CTLA4", "TOX"],
            "treg": ["FOXP3", "IL2RA", "CTLA4", "CCR4"],
            "th1": ["TBX21", "CD4"],
            "th2": ["GATA3", "IL4", "IL5", "IL13", "CCR4"],
            "th17": ["RORC", "KLRB1"],
            "nk_like": ["KLRD1", "KLRF1", "FCGR3A", "NCAM1", "KLRC1"],
            "tissue_resident": ["CD69"],
            "proliferating": ["MKI67"],
            "cd8_lineage": ["CD8A", "CD8B"],
            "cd4_lineage": ["CD4"],
        },
    },
    "endothelial": {
        "label": "Endothelial/pericyte",
        "source": "subcluster_cl1_endothelial.py",
        "clusters": ["1"],
        "resolution": 0.3,
        "n_pcs": 15,
        "filter_genes": ["PECAM1", "VWF", "KDR"],
        "feature_genes": [
            "PECAM1",
            "VWF",
            "KDR",
            "SOX17",
            "AQP1",
            "RAMP2",
            "ESM1",
            "ANGPT2",
            "CXCR4",
            "CCL19",
            "CCL21",
            "CXCL12",
            "ACTA2",
            "MYH11",
            "PDGFRB",
            "ZEB1",
            "ZEB2",
            "SNAI1",
            "FN1",
            "S100A4",
            "MKI67",
            "TOP2A",
        ],
        "programs": {
            "pan_endothelial": ["PECAM1", "VWF", "KDR"],
            "arterial": ["SOX17"],
            "capillary": ["AQP1", "RAMP2"],
            "tip_sprouting": ["ESM1", "ANGPT2", "CXCR4"],
            "hev_like": ["CCL19", "CCL21"],
            "activated_inflam": ["CXCL12"],
            "pericyte_mural": ["ACTA2", "MYH11", "PDGFRB"],
            "endmt": ["ZEB1", "ZEB2", "SNAI1", "FN1", "S100A4"],
            "proliferating": ["MKI67", "TOP2A"],
        },
    },
    "myeloid": {
        "label": "Myeloid/DC",
        "source": "subcluster_cl2_11_12_myeloid_dc.py",
        "clusters": ["2", "11", "12"],
        "resolution": 0.4,
        "n_pcs": 15,
        "filter_genes": [
            "CD68",
            "CD163",
            "CD14",
            "LYZ",
            "AIF1",
            "C1QA",
            "CSF1R",
            "ITGAM",
            "MRC1",
            "MARCO",
            "FCER1G",
            "CTSS",
            "LILRA4",
            "PLD4",
            "CLEC9A",
            "CLEC10A",
            "CD1C",
            "CD1A",
            "LAMP3",
            "IRF8",
        ],
        "feature_genes": [
            "CD68",
            "CD14",
            "LYZ",
            "AIF1",
            "C1QA",
            "C1QC",
            "CSF1R",
            "ITGAM",
            "FCER1G",
            "CTSS",
            "MNDA",
            "CD86",
            "CD80",
            "IL1B",
            "TNF",
            "CD163",
            "MRC1",
            "MARCO",
            "ARG1",
            "IL10",
            "TREM2",
            "CD9",
            "S100A8",
            "VCAN",
            "LILRA4",
            "PLD4",
            "SPIB",
            "IRF8",
            "TCF4",
            "ITM2C",
            "CLEC9A",
            "CLEC10A",
            "CD1C",
            "FCER1A",
            "IRF4",
            "CD1A",
            "LAMP3",
            "CCR7",
            "CCL19",
            "STAT1",
            "MX1",
            "IFIT3",
            "IRF1",
            "MKI67",
            "TOP2A",
            "CENPF",
        ],
        "programs": {
            "core_macrophage": [
                "CD68",
                "CD14",
                "LYZ",
                "AIF1",
                "C1QA",
                "C1QC",
                "CSF1R",
                "ITGAM",
                "FCER1G",
                "CTSS",
            ],
            "macrophage_M1": ["CD86", "CD80", "IL1B", "TNF"],
            "macrophage_M2": ["CD163", "MRC1", "MARCO", "ARG1", "IL10", "TREM2"],
            "monocyte": ["S100A8", "VCAN", "MNDA", "CD14"],
            "pDC": ["LILRA4", "PLD4", "SPIB", "IRF8", "TCF4", "ITM2C"],
            "cDC1": ["CLEC9A", "IRF8"],
            "cDC2": ["CLEC10A", "CD1C", "FCER1A", "IRF4"],
            "mregDC": ["LAMP3", "CCR7", "CCL19"],
            "langerhans": ["CD1A"],
            "ifn_response": ["STAT1", "MX1", "IFIT3", "IRF1"],
            "proliferating": ["MKI67", "TOP2A", "CENPF"],
        },
    },
    "tumor": {
        "label": "Tumor/myoepithelial",
        "source": "subcluster_cl3_4_10_combined.py",
        "clusters": ["3", "4", "10"],
        "resolution": 0.3,
        "n_pcs": 15,
        "filter_genes": [
            "KRT8",
            "EPCAM",
            "CDH1",
            "KRT7",
            "TACSTD2",
            "KRT5",
            "KRT14",
            "ACTA2",
            "MYH11",
        ],
        "feature_genes": [
            "KRT8",
            "EPCAM",
            "CDH1",
            "KRT7",
            "TACSTD2",
            "ESR1",
            "PGR",
            "FOXA1",
            "GATA3",
            "ANKRD30A",
            "AGR3",
            "MLPH",
            "BCL2",
            "AREG",
            "CCND1",
            "KIT",
            "ALDH1A3",
            "KRT23",
            "SFRP1",
            "ERBB2",
            "KRT5",
            "KRT14",
            "KRT6B",
            "EGFR",
            "ACTA2",
            "MYH11",
            "MYLK",
            "ACTG2",
            "OXTR",
            "MKI67",
            "TOP2A",
            "CENPF",
            "HMGA1",
            "ZEB1",
            "ZEB2",
            "SNAI1",
            "FN1",
            "S100A4",
            "POSTN",
            "CEACAM6",
            "TPD52",
            "ERBB3",
            "CDKN1A",
        ],
        "programs": {
            "luminal_mature": [
                "ESR1",
                "PGR",
                "FOXA1",
                "GATA3",
                "ANKRD30A",
                "AGR3",
                "MLPH",
                "BCL2",
                "AREG",
            ],
            "luminal_progenitor": ["KIT", "ALDH1A3", "KRT23", "SFRP1"],
            "her2": ["ERBB2"],
            "basal_triple_neg": ["KRT5", "KRT14", "KRT6B", "EGFR"],
            "myoepithelial": ["ACTA2", "MYH11", "MYLK", "ACTG2", "OXTR"],
            "pan_epithelial": ["KRT8", "EPCAM", "CDH1", "KRT7", "TACSTD2"],
            "proliferating": ["MKI67", "TOP2A", "CENPF", "HMGA1"],
            "emt": ["ZEB1", "ZEB2", "SNAI1", "FN1", "S100A4", "POSTN"],
            "cancer_specific": ["CEACAM6", "TPD52", "AGR3", "MLPH"],
            "stress_g1arrest": ["CDKN1A"],
        },
    },
    "bplasma": {
        "label": "B/plasma",
        "source": "subcluster_cl5_8_bplasma.py",
        "clusters": ["5", "8"],
        "resolution": 0.4,
        "n_pcs": 15,
        "filter_genes": [
            "MS4A1",
            "CD79A",
            "CD79B",
            "CD19",
            "BANK1",
            "TCL1A",
            "CD27",
            "MZB1",
            "TNFRSF17",
            "CD38",
            "PRDM1",
            "IRF4",
            "IGHG1",
            "IGHM",
        ],
        "feature_genes": [
            "MS4A1",
            "CD79A",
            "CD79B",
            "CD19",
            "BANK1",
            "TCL1A",
            "IGHD",
            "FCER2",
            "SELL",
            "CR2",
            "CD27",
            "CD83",
            "CD40",
            "BCL6",
            "CXCR5",
            "AICDA",
            "RGS13",
            "FCRL4",
            "ITGAX",
            "TBX21",
            "MZB1",
            "TNFRSF17",
            "PRDM1",
            "IRF4",
            "CD38",
            "XBP1",
            "SLAMF7",
            "IGHG1",
            "IGHM",
            "IGHA1",
            "IGKC",
            "JCHAIN",
            "MKI67",
            "TOP2A",
            "CENPF",
            "HMGA1",
            "HLA-DRA",
            "CD74",
            "CXCR4",
        ],
        "programs": {
            "pan_B": ["MS4A1", "CD79A", "CD79B", "CD19", "BANK1"],
            "naive_B": ["TCL1A", "IGHD", "FCER2", "SELL", "CR2"],
            "memory_B": ["CD27", "CD83"],
            "germinal_center": ["BCL6", "CXCR5", "AICDA", "RGS13"],
            "atypical_B": ["FCRL4", "ITGAX", "TBX21"],
            "plasma": ["MZB1", "TNFRSF17", "PRDM1", "IRF4", "CD38", "XBP1", "SLAMF7"],
            "igG": ["IGHG1"],
            "igM": ["IGHM"],
            "proliferating": ["MKI67", "TOP2A", "CENPF", "HMGA1"],
            "antigen_presentation": ["HLA-DRA", "CD74"],
        },
    },
    "caf": {
        "label": "CAF/adipocyte",
        "source": "subcluster_cl6_7_13_14_caf_adipo.py",
        "clusters": ["6", "7", "13", "14"],
        "resolution": 0.4,
        "n_pcs": 15,
        "filter_genes": [
            "LUM",
            "PDGFRA",
            "PDGFRB",
            "FBLN1",
            "MMP2",
            "POSTN",
            "VCAN",
            "ACTA2",
            "MYH11",
            "CXCL12",
            "C1R",
            "C1S",
            "LRRC15",
            "DPT",
            "ADIPOQ",
            "LPL",
            "PPARG",
            "ADH1B",
            "TIMP4",
        ],
        "feature_genes": [
            "LUM",
            "PDGFRA",
            "PDGFRB",
            "FBLN1",
            "CCDC80",
            "DPT",
            "FN1",
            "VCAN",
            "SFRP4",
            "CAV1",
            "ACTA2",
            "MYH11",
            "MYLK",
            "LRRC15",
            "POSTN",
            "MMP2",
            "CXCL12",
            "CXCL13",
            "IL6",
            "C1R",
            "C1S",
            "ZEB1",
            "ZEB2",
            "SNAI1",
            "S100A4",
            "ADIPOQ",
            "LPL",
            "PPARG",
            "ADH1B",
            "TIMP4",
            "UCP1",
            "CD9",
            "PECAM1",
            "PTPRC",
            "CD3E",
            "EPCAM",
            "KRT8",
            "LYZ",
            "MKI67",
            "TOP2A",
            "CENPF",
        ],
        "programs": {
            "pan_CAF": ["LUM", "PDGFRA", "PDGFRB", "FBLN1", "CCDC80", "DPT"],
            "myCAF": ["ACTA2", "MYH11", "MYLK", "LRRC15", "POSTN"],
            "iCAF": ["CXCL12", "CXCL13", "IL6"],
            "complement_caf": ["C1R", "C1S", "FBLN1", "DPT"],
            "matrix_remodel": ["MMP2", "POSTN", "VCAN", "FN1"],
            "pericyte_mural": ["ACTA2", "MYH11", "PDGFRB", "CAV1", "MYLK"],
            "emt": ["ZEB1", "ZEB2", "SNAI1", "S100A4", "FN1"],
            "adipocyte": ["ADIPOQ", "LPL", "PPARG", "ADH1B", "TIMP4"],
            "preadipo": ["PDGFRA", "CD9"],
            "proliferating": ["MKI67", "TOP2A", "CENPF"],
        },
    },
    "mast": {
        "label": "Mast",
        "source": "subcluster_cl9_mast.py",
        "clusters": ["9"],
        "resolution": 0.3,
        "n_pcs": 12,
        "filter_genes": ["TPSAB1", "CPA3", "KIT", "FCER1A", "GATA2", "CTSG"],
        "feature_genes": [
            "TPSAB1",
            "CPA3",
            "KIT",
            "FCER1A",
            "GATA2",
            "CTSG",
            "CD9",
            "IL4",
            "IL13",
            "TNF",
            "CD69",
            "IL6",
            "CCL5",
            "PTGS2",
            "AREG",
            "CSF1",
            "STAT1",
            "MX1",
            "IFIT3",
            "IRF1",
            "ISG15",
            "MKI67",
            "TOP2A",
            "CENPF",
            "HMGA1",
            "PDGFRB",
            "LUM",
            "FN1",
            "LYZ",
            "CD68",
            "S100A8",
            "FCGR3B",
        ],
        "programs": {
            "mast_core": ["TPSAB1", "CPA3", "KIT", "FCER1A", "GATA2", "CTSG", "CD9"],
            "effector_activation": [
                "IL4",
                "IL13",
                "TNF",
                "CD69",
                "IL6",
                "CCL5",
                "PTGS2",
                "AREG",
                "CSF1",
            ],
            "ifn_response": ["STAT1", "MX1", "IFIT3", "IRF1", "ISG15"],
            "proliferating": ["MKI67", "TOP2A", "CENPF", "HMGA1"],
        },
    },
}
